version: '3'
services:
  marklogic:
    image: marklogiccommunity/marklogic-datahub:${ML_VERSION}
    build:
      context: .
      dockerfile: ./.travis/Dockerfile
    ports:
      - "5005:5005"
      - "8000-8020:8000-8020"
    volumes:
      - .:/marklogic-data-hub
